project/application/urls.py
from sys import path

from django.conf.urls import url, include
from django.contrib import admin

from django.conf import settings
from django.conf.urls import include, url

urlpatterns = [
    url(r'^admin/', admin.site.urls),

    url(r'', include('core.urls', namespace='core')),
    url(r'^categories/', include('categories.urls', namespace='categories')),
    url(r'^questions/', include('questions.urls', namespace='questions')),

    url('', include('social_django.urls')),

    url(r'^\.well-known/', include('letsencrypt.urls')),

]

if settings.DEBUG:
    import debug_toolbar
    urlpatterns = [
        url(r'^__debug__/', include(debug_toolbar.urls)),
    ] + urlpatterns

project/categories/urls.py
from django.conf.urls import url, include
from django.contrib import admin

from categories import views as categories_views

urlpatterns = [
    url(r'^(?P<pk>\d+)/$', categories_views.category_detail, name='category_detail'),
    url(r'^$', categories_views.CategoryList.as_view(), name='category_list'),
    url(r'^create/$', categories_views.CategoryCreate.as_view(), name='category_create'),

    url(r'^category_list_front/$', categories_views.category_list_front, name='category_list_front'),
    url(r'^category_create_front/$', categories_views.category_create_front, name='category_create_front'),
]
#category_list

project/core/urls.py
from django.conf.urls import url, include

from django.contrib.auth.decorators import login_required
from oauthlib.uri_validate import path

from core import views as core_views

from jsonrpc import jsonrpc_site

urlpatterns = [
    url(r'^$', core_views.main_page, name='main_page'),
    url(r'^login/$', core_views.Login.as_view(), name='login'),
    url(r'^logout/$', core_views.Logout.as_view(), name='logout'),
    url(r'^register/$', core_views.register, name='register'),
    url(r'^profile/$', login_required(core_views.profile), name='profile'),

    url(r'^login_front/$', core_views.login_front, name='login_front'),

    url(r'^api/$', jsonrpc_site.dispatch, name='api'),
]

project/questions/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.contrib.auth.decorators import login_required
from questions import views as questions_views

from jsonrpc import jsonrpc_site

urlpatterns = [
    url(r'^(?P<pk>\d+)/detail/$', questions_views.question_content, name='question_content'),
    url(r'^create/$', login_required(questions_views.QuestionCreate.as_view()), name='question_create'),
    url(r'^(?P<pk>\d+)/edit/$', questions_views.QuestionEdit.as_view(), name='question_edit'),
    url(r'^$', questions_views.question_list, name='question_list'),
    url(r'^(?P<pk>\d+)/comments/$', questions_views.question_comments, name='question_comments'),
    url(r'^(?P<pk>\d+)/likes/$', questions_views.QuestionLikeAjaxView.as_view(), name='question_likes'),

    url(r'^question_list_front/$', questions_views.question_list_front, name='question_list_front'),

    #url(r'^api/$', jsonrpc_site.dispatch, name='api'),
]

project/questions/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.db import models
from django.conf import settings


class QuestionQuerySet(models.QuerySet):
    def annotate_manager(self):
        qs = self.select_related('author')
        qs = qs.prefetch_related('categories')
        qs = qs.annotate(likes_count=models.Count('likes', distinct=True),
                         answers_count=models.Count('answers', distinct=True))
        return qs

    def filt_del(self, autho):
        if autho.is_authenticated():
            return self.filter(models.Q(author=autho) | models.Q(is_archive=False))
        else:
            return self.filter(models.Q(is_archive=False))

    def get_stats(self):
        return self.aggregate(likes_count=models.Count('likes', distinct=True),
                              answers_count=models.Count('answers', distinct=True))


class QuestionFile(models.Model):
    file_mime = models.CharField(max_length=72)
    file_key = models.CharField(max_length=72)
    file_content = models.FileField(null = True, upload_to="files")

class Question(models.Model):
    name = models.CharField(max_length=255, verbose_name=u'Название вопроса')
    author = models.ForeignKey(
        settings.AUTH_USER_MODEL,
        related_name='questions',
        verbose_name=u'Автор'
    )
    categories = models.ManyToManyField(
        'categories.Category',
        blank=False,
        related_name='questions',
        verbose_name=u'Категории'
    )
    is_archive = models.BooleanField(default=False, verbose_name=u'Блок в архиве')
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)
    data = models.TextField(verbose_name=u'Содержимое вопроса')

    photo = models.FileField(null=True, upload_to="photos")
    files = models.ManyToManyField( QuestionFile)

    objects = QuestionQuerySet.as_manager()

    class Meta:
        verbose_name=u'Вопрос'
        verbose_name_plural=u'Вопросы'
        ordering='name', 'id'

    def __unicode__(self):

        return self.name

class Like(models.Model):
    author = models.ForeignKey(
        settings.AUTH_USER_MODEL,
        related_name='likes',
        verbose_name=u'Like'
    )
    questions = models.ForeignKey(
        'questions.Question',
        related_name='likes',
        verbose_name=u'Likes'
    )
    class Meta:
        verbose_name = u'Лайк'
        verbose_name_plural = u'Лайки'

    def __unicode__(self):
        return self.name


class Answer(models.Model):
    name = models.CharField(max_length=255, verbose_name=u'Название ответа')
    author = models.ForeignKey(
        settings.AUTH_USER_MODEL,
        related_name='answers',
        verbose_name=u'Автор'
    )
    answers = models.ForeignKey(
        'questions.Question',
        related_name='answers',
        verbose_name=u'Ответы'
    )
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)
    data = models.TextField(verbose_name=u'Содержимое ответа', )

    class Meta:
        verbose_name = u'Ответ'
        verbose_name_plural = u'Ответы'
        ordering = 'name', 'id'

    def __unicode__(self):
        return self.name

project/questions/views.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.shortcuts import render, HttpResponse, redirect, get_object_or_404, reverse
from .models import Question, Answer, Like
from django import forms
from django.views.generic import UpdateView, CreateView, DetailView, View
from django.core.files.base import ContentFile

from django.shortcuts import render
from jsonrpc import jsonrpc_method
from jsonrpc.exceptions import Error
from django.http import JsonResponse
from django.core.serializers import serialize
import json
from jsonrpc import jsonrpc_method
import base64
import hashlib
from adjacent.utils import get_connection_parameters
from adjacent.client import Client
import cProfile


@jsonrpc_method('api.upload_file')
def upload_file(request, file_content, file_name):
    content = base64.b64decode(file_content).decode('utf-8')
    key = generate_key(file_name)
    quest = Question.objects.all().first()

    quest.photo.save("{}/{}".format(quest.id, key), ContentFile(content.encode('utf-8')))
    return content.decode('utf8')


def generate_key(filename):
    h = hashlib.new('md5')
    h.update(filename.encode('utf-8'))
    return h.hexdigest()


@jsonrpc_method('api.question_content')
def question_content(request, pk):
    question = get_object_or_404(Question, id=pk)
    answers = question.answers.all().order_by('created').select_related('author')

    answer = Answer()

    context = {
         'categories': question.categories.all(),
         'question': question,
         'answers': answers,
         'token': get_connection_parameters(request.user)['token'],
    }

    if request.method == 'GET':
        form = AnswerForm(instance=answer)
        context['form'] = form
        # return json.loads(serialize('json', [context['question']]))
        return render(request, 'questions/question_content.html', context)

    elif request.method == 'POST':
        answer.answers = question
        form = AnswerForm(request.POST, instance=answer)
        if form.is_valid():
            answer = form.save(commit=False)
            answer.author = request.user
            answer.save()
            context['form'] = form

            client = Client()
            client.publish('answers_question_{}'.format(question.pk), {})
            client.send()

            # return json.loads(serialize('json', [context['question']]))
            return redirect('questions:question_content', pk=question.id)
        else:
            context['form'] = form
            # return json.loads(serialize('json', [context['question']]))
            return render(request, 'questions/question_content.html', context)


# @jsonrpc_method('api.question_list')
# def question_list(request):
#     context = {
#         'questions': Question.objects.all().order_by("-created").annotate_manager().filt_del(request.user),
#     }
#     return json.loads(serialize('json', context['questions']))


def question_list_front(request):
    context = {
        'questions': serialize('json', Question.objects.all().order_by("-created").filter(is_archive=False)),
    }
    return JsonResponse(context)


def question_list(request):
    context = {
        'questions': Question.objects.all().order_by("-created").annotate_manager().filt_del(request.user),
    }
    return render(request, 'questions/question_list.html', context)


@jsonrpc_method('api.question_comments')
def question_comments(request, pk):
    question = get_object_or_404(Question, id=pk)
    answers = question.answers.all()
    context = {
        'categories': question.categories.all(),
        'question':  question,
        'answers': answers.order_by('created'),
    }
    return json.loads(serialize('json', context['answers']))


# def question_comments(request, pk):
    # question = get_object_or_404(Question, id=pk)
    # answers = question.answers.all()
    # context = {
    #     'categories': question.categories.all(),
    #     'question': question,
    #     'answers': answers.order_by('created'),
    # }
    # return render(request, 'questions/commentsdiv.html', context)


class AnswerForm(forms.ModelForm):
    class Meta:
        model=Answer
        fields = 'name', 'data'


class QuestionCreate(CreateView):

    model = Question
    fields = 'name', 'categories', 'is_archive', 'data',
    context_object_name = 'question'
    template_name = 'questions/question_create.html'

    def form_valid(self, form):
        form.instance.author = self.request.user
        return super(QuestionCreate, self).form_valid(form)

    def get_success_url(self):
        return reverse('questions:question_content', kwargs={'pk': self.object.pk})


class QuestionEdit(UpdateView):

    model = Question
    fields = 'name', 'categories', 'is_archive', 'data',
    context_object_name = 'question'
    template_name = 'questions/question_edit.html'

    def get_queryset(self):
        queryset=super(QuestionEdit, self).get_queryset()
        queryset=queryset.filter(author=self.request.user)
        return queryset

    def get_success_url(self):
        return reverse('questions:question_content', kwargs = { 'pk': self.object.pk})

    def form_valid(self, form):
        response = super(QuestionEdit, self).form_valid(form)
        return HttpResponse("OK")


class QuestionLikeAjaxView(View):

    def dispatch(self, request, pk=None, *args, **kwargs):
        self.question_object = get_object_or_404(Question, id=pk)
        return super(QuestionLikeAjaxView, self).dispatch(request, *args, **kwargs)

    def post(self, pk):
        if not self.question_object.likes.filter(author=self.request.user).exists():
            like = Like()
            like.questions = self.question_object
            like.author = self.request.user
            like.save()
        return HttpResponse(Like.objects.filter(questions=self.question_object).count())

project/questions/templates/questions/base_questions.html
{% extends "core/base.html" %}

{% block title %}Questions{% endblock %}

project/questions/templates/questions/commentsdiv.html
{% for ans in answers %}
    <div class="alert alert-primary" role="alert" >
        <h4>Name: {{ ans.name }}</h4>{{ ans.data }}
        <hr>
        <p class="text-muted small mb-0">By "{{ ans.author }}" in {{ ans.created }}</p>
    </div>
{% endfor %}

project/questions/templates/questions/question_content.html
{% extends "questions/base_questions.html" %}
{% load crispy_forms_tags %}
{% block header %}{{ question.name }}{% endblock %}
{% load static %}

{% block content %}
    <div>(From categories:
        {% for category in categories %}

            <a href="{% url "categories:category_detail" pk=category.id %}">{{ category.name }}</a>
            {% if not forloop.last %}, {% endif %}
        {% endfor %})
    </div>
        <div class="alert alert-info" role="alert">
            {{ question.data }}
            <hr>
            <div class="row">
                <div class="col-11">
                    <p class="text-muted small mb-0">By "{{ question.author }}" in {{ question.created }} |
                        Likes: <span id="likes-{{ question.id }}">{{ question.likes.count }}</span>
                        <button class="btn ajaxlike" data-url="{% url "questions:question_likes" pk=question.id %}" data-questionid="{{ question.id }}">Лайк!</button>
                    </p>
                </div>
                <div class="col-1">

                    {% if question.author == user %}


                        <button type="button" class="text-muted mb-0 btn-group-sm btn-outline-secondary" data-toggle="modal" data-target="#myModal">
                            Edit
                        </button>
                        <div class="modal fade" id="myModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
                            <div class="modal-dialog" role="document">
                                <div class="modal-content">
                                    <div class="modal-header">
                                        <h4 class="modal-title" id="myModalLabel">Edit your question</h4>
                                    </div>
                                <div class="modal-body question-edit" method="post" data-url="{% url "questions:question_edit" pk=question.id %}">
                                </div>


                                </div>
                            </div>
                        </div>



                    {% endif %}
                </div>
            </div>
        </div>


    <br>


    <br>
    <h3>Answers:</h3>
{#    <div class="autoload" data-url="{% url "questions:question_comments" pk=question.id %}">#}
{#        {%  include 'questions/commentsdiv.html' %}#}
{#    </div>#}

    <script src="{% static "sockjs/sockjs.js" %}"></script>
    <script src="{% static "centrifuge/centrifuge.js" %}"></script>

    <div class="answers"
         data-url="{% url "questions:question_comments" pk=question.id %}"
         data-pk="{{ question.id }}"
         data-token="{{ token }}"
    ></div>


    <br>

    <div>
    <form action="" method="post">
        {% csrf_token %}
            {{ form|crispy   }}
            <button type="submit" class="btn btn-secondary">Answer.</button>
    </form>
    </div>


    <br>
{% endblock %}

project/questions/templates/questions/question_create.html
{% extends "questions/base_questions.html" %}
{% load crispy_forms_tags %}
{% block header %}Create your question{% endblock %}

{% block content %}
    <form action="" method="post">
        {% csrf_token %}
        {{ form|crispy }}
        <button type="submit" class="btn btn-primary">Create.</button>
    </form>
    <br>
{% endblock %}

project/questions/templates/questions/question_edit.html
{% load crispy_forms_tags %}

<form action="" method="post" class="ajaxform" data-url="{% url "questions:question_edit" pk=question.id %}">
    {% csrf_token %}
    {{ form|crispy }}
    <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
    <button type="submit" class="btn btn-primary">Edit</button>
</form>
<script>

$('#id_categories').chosen();
</script>
<br>

project/questions/templates/questions/question_edit_old.html
{% extends "questions/base_questions.html" %}
{% load crispy_forms_tags %}
{% block header %}Edit your question: {{ question }}{% endblock %}

{% block content %}
    <form action="" method="post" class="ajaxform" data-url="{% url "questions:question_edit" pk=question.id %}">
        {% csrf_token %}
        {{ form|crispy }}
        <button type="submit" class="btn btn-primary">Edit.</button>

    </form>
    <br>
{% endblock %}

project/questions/templates/questions/question_list.html
{% extends "questions/base_questions.html" %}

{% block header %}Question list{% endblock %}

{% block content %}
    {% for question in questions %}
        <div class="container">
            <div class="alert alert-secondary">
                <a href="{% url "questions:question_content" pk=question.id %}" class="alert-link">{{ question }}</a>
                <hr>
                <p class="text-muted small mb-0">By "{{ question.author }}" in {{ question.created }} | Likes: {{ question.likes_count }}</p>
            </div>
        </div>

    {% endfor %}
{% endblock %}