project/application/urls.py
from sys import path

from django.conf.urls import url, include
from django.contrib import admin

from django.conf import settings
from django.conf.urls import include, url

urlpatterns = [
    url(r'^admin/', admin.site.urls),

    url(r'', include('core.urls', namespace='core')),
    url(r'^categories/', include('categories.urls', namespace='categories')),
    url(r'^questions/', include('questions.urls', namespace='questions')),

    url('', include('social_django.urls')),

    url(r'^\.well-known/', include('letsencrypt.urls')),

]

if settings.DEBUG:
    import debug_toolbar
    urlpatterns = [
        url(r'^__debug__/', include(debug_toolbar.urls)),
    ] + urlpatterns

project/categories/urls.py
from django.conf.urls import url, include
from django.contrib import admin

from categories import views as categories_views

urlpatterns = [
    url(r'^(?P<pk>\d+)/$', categories_views.category_detail, name='category_detail'),
    url(r'^$', categories_views.CategoryList.as_view(), name='category_list'),
    url(r'^create/$', categories_views.CategoryCreate.as_view(), name='category_create'),

    url(r'^category_list_front/$', categories_views.category_list_front, name='category_list_front'),
    url(r'^category_create_front/$', categories_views.category_create_front, name='category_create_front'),
]
#category_list

project/core/urls.py
from django.conf.urls import url, include

from django.contrib.auth.decorators import login_required
from oauthlib.uri_validate import path

from core import views as core_views

from jsonrpc import jsonrpc_site

urlpatterns = [
    url(r'^$', core_views.main_page, name='main_page'),
    url(r'^login/$', core_views.Login.as_view(), name='login'),
    url(r'^logout/$', core_views.Logout.as_view(), name='logout'),
    url(r'^register/$', core_views.register, name='register'),
    url(r'^profile/$', login_required(core_views.profile), name='profile'),

    url(r'^login_front/$', core_views.login_front, name='login_front'),

    url(r'^api/$', jsonrpc_site.dispatch, name='api'),
]

project/questions/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.contrib.auth.decorators import login_required
from questions import views as questions_views

from jsonrpc import jsonrpc_site

urlpatterns = [
    url(r'^(?P<pk>\d+)/detail/$', questions_views.question_content, name='question_content'),
    url(r'^create/$', login_required(questions_views.QuestionCreate.as_view()), name='question_create'),
    url(r'^(?P<pk>\d+)/edit/$', questions_views.QuestionEdit.as_view(), name='question_edit'),
    url(r'^$', questions_views.question_list, name='question_list'),
    url(r'^(?P<pk>\d+)/comments/$', questions_views.question_comments, name='question_comments'),
    url(r'^(?P<pk>\d+)/likes/$', questions_views.QuestionLikeAjaxView.as_view(), name='question_likes'),

    url(r'^question_list_front/$', questions_views.question_list_front, name='question_list_front'),

    #url(r'^api/$', jsonrpc_site.dispatch, name='api'),
]

project/core/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals
from django import forms
from django.db import models

# Create your models here.
from django.contrib.auth.models import AbstractUser

class User(AbstractUser):
    
    pass

project/core/views.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.shortcuts import render, HttpResponse, redirect, get_object_or_404
from django.contrib.auth.views import LoginView, LogoutView
from django.contrib.auth.hashers import check_password
from django.contrib.auth.forms import UserCreationForm, UserChangeForm
from django.views.generic.edit import FormView
from .models import User
from questions.models import Question
from django.db import models
import json
from django.http import JsonResponse, HttpResponseForbidden
from django.views.decorators.csrf import csrf_exempt

from uuid import uuid4


def main_page(request):
    context = {}
    context['name'] = 'Main page'
    questions = Question.objects.all().filt_del(request.user).order_by("-created")[0:10].annotate_manager()
    context['questions'] = questions
    if request.user.is_authenticated():
        context['auth_url'] = 'core:profile'
        context['auth_url_name'] = 'Profile'
    else:
        context['auth_url'] = 'core:login'
        context['auth_url_name'] = 'Login'
    return render(request, 'core/main_page.html', context)


class Login(LoginView):

    template_name = 'core/login.html'


@csrf_exempt
def login_front(request):

    if request.method == 'POST':

        data = json.loads(request.body)
        username = data['login']
        password = data['password']
        if not User.objects.filter(username=username).exists():
            return HttpResponseForbidden('error')

        user = get_object_or_404(User, username=username)

        if check_password(password, user.password):
            return JsonResponse({'token': uuid4()})
        else:
            return HttpResponseForbidden('error')




class Logout(LogoutView):

    template_name = 'core/logout.html'


class RegisterForm(UserCreationForm):
    template_name = 'core/register.html'

    class Meta:
        model = User
        fields = ("username", "email", "first_name", "last_name", "password1", "password2")


def register(request):
    us = User()

    if request.method == 'GET':
        form = RegisterForm(instance = us)
        return render(request, 'core/register.html', {'form' : form})

    elif request.method == 'POST':
        form = RegisterForm(request.POST, instance = us)
        if form.is_valid():
            us = form.save()
            return redirect('core:login')
        else:
            return render(request, 'core/register.html', {'form': form})


def profile(request):
    quest = Question.objects.filter(author=request.user).aggregate(question_count=models.Count('id', distinct=True))
    questions = Question.objects.filter(author=request.user)
    context = {
        'quest': quest,
        'questions': questions,
        'client': request.user,
    }
    return render(request, 'core/profile.html', context)

project/core/templates/core/base.html
{% load static %}

<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <meta name="csrf" content="{{ csrf_token }}">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="{% static "chosen/chosen.css" %}">
    <link rel="stylesheet" href="{% static "bootstrap/bootstrap-chosen.css" %}">
    <link rel="stylesheet" href="{% static "bootstrap/dist/css/bootstrap.min.css" %}">
    <link rel="stylesheet" href="{% static "base.css" %}">


    <title>{% block title %}Front{% endblock %} page of my Site</title>
</head>
<body>

    <header>
      <!-- Fixed navbar -->
      <nav class="navbar navbar-expand-md navbar-dark fixed-top bg-info">
        <a class="navbar-brand" href="{% url "core:main_page" %}"><img src="{% static "photo.png" %}" width="150" height="48" alt="500"></a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarCollapse" aria-controls="navbarCollapse" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarCollapse">
          <ul class="navbar-nav mr-auto">
            <li class="nav-item active">
              <a class="nav-link" href="{% url "categories:category_list" %}">Categories</a>
            </li>
            <li class="nav-item active">
              <a class="nav-link" href="{% url "questions:question_list" %}">Questions</a>
            </li>
            <li class="nav-item active">
              <a class="nav-link" href="{% url "questions:question_create" %}">Create question</a>
            </li>
            <li class="nav-item active">
              <a class="nav-link" href="{% url "categories:category_create" %}">Create category</a>
            </li>
            {% if request.user.is_authenticated %}
                <li class="nav-item active">
                    <a class="nav-link" href="{% url "core:profile" %}">Profile - {{ user.get_full_name }}</a>
                </li>
            {% else %}
                <li class="nav-item active">
                    <a class="nav-link" href="{% url "core:login" %}">Login</a>
                </li>
            {% endif %}

          </ul>

          <!--<form class="form-inline mt-2 mt-md-2">
            <input class="form-control mr-sm-2" type="text" placeholder="Search" aria-label="Search">
            <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
          </form>-->
        </div>
      </nav>
    </header>

    <!-- Begin page content -->
    <main role="main" class="container">

        <h1 class="mt-5">{% block header %}{% endblock %}</h1>
        <p class="lead">
            {% block content %}

            {% endblock %}
        </p>
    </main>

    <footer class="footer">
      <div class="container">
        <span class="text-muted">Made in China. All rights reserved @stackoverflow
        </span>
      </div>
    </footer>


    <script src="{% static "extralib/jquery-3.3.1.min.js" %}"></script>
    <script src="{% static "extralib/popper.min.js" %}" ></script>
    <script src="{% static "js/base.js" %}"></script>
    <script src="{% static "bootstrap/dist/js/bootstrap.min.js" %}"></script>
    <script src="{% static "chosen/chosen.jquery.js" %}"></script>






</body>
</html>





























<!--<h1>Stackoverflow&mdash;{% block titleAll1 %}{% endblock %}</h1>

<h2>{% block title1 %}{% endblock %}</h2>
<div>
    {% block content1 %}{% endblock %}
</div>

<br>
<a href="{% url "core:main_page" %}">Main page</a>
<br>
<h3>Made in China</h3>-->

project/core/templates/core/login.html
{% extends "core/base.html" %}
{% load crispy_forms_tags %}

{% block title %}Login{% endblock %}
{% block header %}Authorization{% endblock %}

{% block content %}
    <div class="row">
        <div class="col-6">
            <form method="post" action="">
                {% csrf_token %}
                {{ form|crispy }}
                <button type="submit" class="btn btn-primary">Login.</button>
                <a href="/login/vk-oauth2"><img src="/static/vk_auth.jpg" width="45" class="avatar-3" data-toggle="tooltip" title="Login via VKontakte"></a>
                <a href="/login/facebook"><img src="/static/facebook_auth.png" width="45" class="avatar-3" data-toggle="tooltip" title="Login via Facebook"></a>
            </form>

        </div>
    </div>
    <br>
    <div>Если вы не имеетe аккаунта, то пройдите регистрацию: <a href="{% url "core:register" %}">ссылка</a></div>
{% endblock %}

project/core/templates/core/logout.html
{% extends "core/base.html" %}

{% load crispy_forms_tags %}

{% block title %}Logout{% endblock %}
{% block header %}Exit{% endblock %}

{% block content %}
    <form method="post" action="">
        {% csrf_token %}
        {{ form|crispy }}
        <button type="submit" class="btn btn-primary">Logout.</button>
    </form>
{% endblock %}

project/core/templates/core/main_page.html
{% extends "core/base.html" %}

{% block title %}Main{% endblock %}
{% block header %}StackOverflow2{% endblock %}
<!--titleAll-->
{% block content %}

    {% for question in questions %}
        <div class="container">
            <div class="alert alert-secondary">
                <a href="{% url "questions:question_content" pk=question.id %}" class="alert-link">{{ question }}</a>
                <hr>
                <div class="text-muted small mb-0 text row">
                    <div class="text-left col-4">By "{{ question.author }}" in {{ question.created }}
                    </div>
                    <div class="text-left col-1">Likes {{ question.likes_count }} </div>
                    <div class="text-right col-7">
                    Categories:
                    {% for category in question.categories.all %}
                        <a href="{% url "categories:category_detail" pk=category.id %}">{{ category.name }}</a>
                        {% if not forloop.last %}, {% endif %}
                    {% endfor %}
                    </div>
                </div>
            </div>
        </div>

    {% endfor %}

{% endblock %}

project/core/templates/core/profile.html
{% extends "core/base.html" %}

{% load crispy_forms_tags %}

{% block title %}Profile{% endblock %}
{% block header %}Your profile{% endblock %}


{% block content %}
    <div>
        <p>Now on this site you created: {{ quest.question_count }} questions {{ user.questions_set.all.get_stats.likes_count }} </p>

    {% for question in questions %}
        <div class="container">
            <div class="alert alert-secondary">
                <a href="{% url "questions:question_content" pk=question.id %}" class="alert-link">{{ question }}</a>
                <hr>
                <p class="text-muted small mb-0">By "{{ question.author }}" in {{ question.created }} | Likes: {{ question.likes_count }}</p>
            </div>
        </div>
    {% endfor %}
    <br>
        <p>Your name: {{ client.first_name }} {{ client.last_name }}</p>
    {% if client.email %}
        <p>Your email: {{ client.email }}</p>
    {% endif %}
    </div>

    <br>
    <div>Exit: <a href="{% url "core:logout" %}">Link</a></div>
{% endblock %}

project/core/templates/core/register.html
{% extends "core/base.html" %}
{% load crispy_forms_tags %}

{% block title %}Register{% endblock %}
{% block header %}Registration{% endblock %}

{% block content %}
    <div class="row">
        <div class="col-6">
            <form method="post" action="">
                {% csrf_token %}
                {{ form|crispy }}

                <button type="submit" class="btn btn-primary">Register.</button>
            </form>
        </div>
    </div>
{% endblock %}